Repository potatoengine/potato, pull requests merged in 2019-09, with the labels that each got.

#123 GitHub Actions for CI
  .github/workflows/build.yml
  .github/workflows/doxygen.yml
Labels: CI

#127 Cleanup build workflow
  .github/workflows/build.yml
  .github/workflows/doxygen.yml
  .github/workflows/main.yml
  source/library/assetdb/private/asset_library.cpp
  source/library/assetdb/private/asset_record.cpp
  source/library/assetdb/private/hash_cache.cpp
  source/library/assetdb/public/potato/assetdb/asset_record.h
  source/library/filesystem/private/native.default.cpp
  source/library/filesystem/private/native.posix.cpp
  source/library/filesystem/public/potato/filesystem/native.h
  source/library/runtime/private/callstack.posix.cpp
  source/library/runtime/private/debug.cpp
Labels: CI

#109 Meta files #98
  .github/workflows/main.yml
  cmake/modules/Findlibuuid.cmake
  resources/materials/basic.json.meta
  resources/materials/debug_line.json.meta
  resources/meshes/cube.obj.meta
  resources/shaders/basic.hlsl.meta
  resources/shaders/common.hlsli.meta
  resources/shaders/debug_line.hlsl.meta
  resources/shaders/depth.hlsli.meta
  resources/shaders/imgui.hlsl.meta
  resources/test.json.meta
  resources/textures/test.png.meta
  source/app/recon/private/converter_app.cpp
  source/app/recon/private/converter_app.h
  source/app/recon/private/converters/convert_copy.h
  source/app/recon/private/converters/convert_hlsl.cpp
  source/app/recon/private/converters/convert_hlsl.h
  source/app/recon/private/converters/convert_ignore.h
  source/app/recon/private/converters/convert_json.h
  source/app/recon/private/converters/convert_model.h
  source/app/recon/public/potato/recon/converter.h
  source/library/assetdb/private/asset_library.cpp
  source/library/foundation/private/RCa11856
  source/library/foundation/public/potato/foundation/CMakeLists.txt
  source/library/runtime/CMakeLists.txt
  source/library/runtime/private/CMakeLists.txt
  source/library/runtime/private/uuid.cpp
  source/library/runtime/public/potato/runtime/uuid.h
  source/library/runtime/tests/CMakeLists.txt
  source/library/runtime/tests/test_uuid.cpp
  test.json.meta
Labels: Feature Request, Feature: Resources

#134 Fix D3D build
  source/librender/CMakeLists.txt
  source/librender/private/d3d11_backend/d3d11_buffer.h
  source/librender/private/d3d11_backend/d3d11_command_list.h
  source/librender/private/d3d11_backend/d3d11_device.h
  source/librender/private/d3d11_backend/d3d11_factory.h
  source/librender/private/d3d11_backend/d3d11_pipeline_state.h
  source/librender/private/d3d11_backend/d3d11_platform.h
  source/librender/private/d3d11_backend/d3d11_resource_view.h
  source/librender/private/d3d11_backend/d3d11_sampler.h
  source/librender/private/d3d11_backend/d3d11_swap_chain.h
  source/librender/private/d3d11_backend/d3d11_texture.h
Labels: Feature: Rendering
